name: test-pr

on:
  workflow_dispatch:
    inputs:
      feature:
        description: Feature
        required: false
        type: string

      client:
        description: Client ID
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ inputs | toJSON }}'
